name: Feature Request
description: Request a new feature.
labels: [feature request]
body:
  - type: markdown
    attributes:
      value: |
        Voy a meter lo que me de la gana
  - type: textarea
    id: description
    attributes:
      label: Feature
      description: Una explicación de la idea así a lo general y luego partes pequeñitas como yo que sé, que redirija a los 5 segundos o hacer x cosita pequeña
      placeholder: Estaría bien añadir x y x por..., Se podría hacer que el div tenga 69 de id porque..., ¿Qué? so...
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternative solutions or implementations
      description: Pues nada eso, alternativas a lo que se ha dicho porque ya sabes que nunca sabes nada
  - type: textarea
    id: additional-context
    attributes:
      label: Other context
      description: Any other context, screenshots, or file uploads that help us understand your feature request.
